name: Tidelift Scanner Example
on:
  issues:
    types: [opened, edited]

jobs:
  tidelift_scanner:
    runs-on: ubuntu-latest
    steps:
      # - uses: macowie/issue_scanner_test@v1 # For external/real usage. Otherwise check out and local path:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tidelift-token: ${{ secrets.TIDELIFT_TOKEN }}
    # permissions:
    #   actions: read
    #   contents: read
    #   issues: write
    #   pull-requests: read
